# Generated by Django 3.2.2 on 2022-01-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('speciality', models.CharField(default='', max_length=100)),
                ('costWard', models.IntegerField(default=0)),
                ('typeGP', models.BooleanField()),
                ('rating', models.IntegerField(default=0)),
                ('contact', models.CharField(default='', max_length=50)),
                ('covid', models.BooleanField()),
                ('availableBeds', models.IntegerField(default=0)),
                ('timings', models.CharField(default='', max_length=100)),
                ('pincode', models.IntegerField(default=0)),
                ('army', models.BooleanField()),
                ('state', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
